
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    # kb_layout = us
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    # numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
    }

}



# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}
#########################custom######################

submap = music

# S = Open
bind = , S, exec, spotify
bind = , S, submap, reset 

# L = Lyrics Mode
# 1. Open Spotify
# 2. Wait a split second
# 3. Send 'Shift+L' (Spotify's lyrics shortcut)
# 4. Make it fullscreen
bind = , L, exec, spotify
bind = , L, exec, sleep 0.5 && hyprctl dispatch sendshortcut SHIFT, L, address:$(hyprctl clients -j | jq -r '.[] | select(.class == "Spotify") | .address')
bind = , L, exec, hyprctl dispatch fullscreen 0
bind = , L, submap, reset

# C = Close
bind = , C, exec, pkill spotify
bind = , C, submap, reset

submap = reset



#DECORATION
#decoration {
 #   active_opacity = 0.90
  #  inactive_opacity = 0.80
#}
#If a window has a specific rule in windowrules.conf, that rule overrides global opacity.

decoration {
    blur {
        enabled = true
        size = 3       # Lower this number (e.g., 3 instead of 8) to reduce blurriness
        passes = 1     # 1 is the lightest setting; higher numbers make it heavier
        vibrancy = 0.1 # Adjusts how much the color pops through
    }
}
